name: HTA Sistemas CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Baixar código
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🔨 Build do projeto
        run: npm run build || echo "Sem build configurado"

      - name: 🚀 Deploy (simulado)
        run: echo "Deploy futuro aqui (SSH / servidor / cloud)"
